### ISSUE TITLE
execSync: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kayarre** [valette/desk#4]
When using the default centos 7 nodejs packages the version is 0.10 and is to old. There should be a minimum version requirement for nodejs. installing the latest version appears to correct the error.

When running "npm run buildAddons" I get the following error.

> desk-server@0.2.0 buildAddons 
> node lib/build.js

/build/desk/desk/lib/build.js:10
execSync("cmake .", {cwd : __dirname + "/cmake"})
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/ksansom/build/desk/desk/lib/build.js:10:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by valette** [comment]
OK!
i'm not sure which minimum version to pick. 4.0 seems like a fair one, doesn't it? I do not use 0.12 anymore.

**Comment by kayarre** [comment]
That works for me.
